# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [2]:
# Import libraries
import numpy as np
import pandas as pd

In [49]:
# Importing the dataset
file_loc = 'Pokemon.csv'
pokemon = pd.read_csv(file_loc)
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [50]:
# your code here
cols_considered = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']
# Total_Check is the column we calculated using summing all the features mentioned in cols_considered list
pokemon['Total_Check'] = pokemon[cols_considered].sum(axis=1)
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total_Check
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,309

In [51]:
# Checking if formula works for all pokemon
print("Number of pokemons differing in total are: ", sum(pokemon['Total'] - pokemon['Total_Check']))

Number of pokemons differing in total are:  0

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [52]:
# your code here
# Unique values in type-1 and type-2
one_hot_cols = [i for i in list(np.concatenate((pokemon['Type 1'].unique(), pokemon['Type 2'].unique()))) if type(i)==str]

In [53]:
# Creating a columns of all the unique values in Type-1 and Type-2
for col in one_hot_cols:
  pokemon[col] = 0

pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,...,Fairy,Fighting,Psychic,Rock,Ghost,Ice,Dragon,Dark,Steel,Flying
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,...,0,0,0,0,0,0,0,0,0,0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,...,0,0,0,0,0,0,0,0,0,0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,...,0,0,0,0,0,0,0,0,0,0
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,...,0,0,0,0,0,0,0,0,0,0
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,...,0,0,0,0,0,0,0,0,0,0

In [54]:
for col in one_hot_cols:
  temp1 = pokemon[pokemon['Type 1'] == col]
  if len(temp1) > 0:
    pokemon.loc[pokemon['Type 1'] == col, col] = 1

  temp2 = pokemon[pokemon['Type 2'] == col]
  if len(temp2) > 0:
    pokemon.loc[pokemon['Type 2'] == col, col] = 1
   
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,...,Fairy,Fighting,Psychic,Rock,Ghost,Ice,Dragon,Dark,Steel,Flying
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,...,0,0,0,0,0,0,0,0,0,0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,...,0,0,0,0,0,0,0,0,0,0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,...,0,0,0,0,0,0,0,0,0,0
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,...,0,0,0,0,0,0,0,0,0,0
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,...,0,0,0,0,0,0,0,0,0,0

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [55]:
one_hot_cols.append('Total')
# your code here
cor_df = pokemon[one_hot_cols].corr()
cor_df

,Grass,Fire,Water,Bug,Normal,Poison,Electric,Ground,Fairy,Fighting,...,Ice,Rock,Dark,Water,Electric,Fire,Ghost,Bug,Normal,Total
Grass,1.000000,-0.108248,-0.126894,-0.034430,-0.117156,0.110372,-0.078818,-0.097033,-0.048756,-0.051171,...,-0.027476,-0.072829,-0.048339,-0.126894,-0.078818,-0.108248,0.075316,-0.034430,-0.117156,-0.052592
Fire,-0.108248,1.000000,-0.114850,-0.060536,-0.085097,-0.085471,-0.057104,-0.022621,-0.067651,0.051130,...,-0.065851,-0.064677,-0.020368,-0.114850,-0.057104,1.000000,-0.013459,-0.060536,-0.085097,0.078726
Water,-0.126894,-0.114850,1.000000,-0.123983,-0.154994,-0.073986,-0.069109,-0.006844,-0.067703,-0.073778,...,0.000242,0.011447,-0.028548,1.000000,-0.069109,-0.114850,-0.077314,-0.123983,-0.154994,-0.021665
Bug,-0.034430,-0.060536,-0.123983,1.000000,-0.120219,0.121210,-0.045111,-0.063544,-0.072148,-0.048645,...,-0.070229,-0.003706,-0.082062,-0.123983,-0.045111,-0.060536,-0.058915,1.000000,-0.120219,-0.145781
Normal,-0.117156,-0.085097,-0.154994,-0.120219,1.000000,-0.110800,-0.067737,-0.102044,-0.001720,-0.071687,...,-0.085366,-0.106877,-0.099751,-0.154994,-0.067737,-0.085097,-0.094420,-0.120219,1.000000,-0.105331
Poison,0.110372,-0.085471,-0.073986,0.121210,-0.110800,1.000000,-0.074838,-0.053878,-0.066495,-0.039613,...,-0.064726,-0.081036,-0.018227,-0.073986,-0.074838,-0.085471,0.008736,0.121210,-0.110800,-0.090441
Electric,-0.078818,-0.057104,-0.069109,-0.045111,-0.067737,-0.074838,1.000000,-0.059420,-0.035541,-0.068775,...,-0.033382,-0.072188,-0.067375,-0.069109,1.000000,-0.057104,-0.041592,-0.045111,-0.067737,0.020971
Ground,-0.097033,-0.022621,-0.006844,-0.063544,-0.102044,-0.053878,-0.059420,1.000000,-0.069360,-0.080531,...,-0.003872,0.072085,-0.023480,-0.006844,-0.059420,-0.022621,-0.035908,-0.063544,-0.102044,0.015060
Fairy,-0.048756,-0.067651,-0.067703,-0.072148,-0.001720,-0.066495,-0.035541,-0.069360,1.000000,-0.061108,...,-0.051232,0.002212,-0.059864,-0.067703,-0.035541,-0.067651,-0.056665,-0.072148,-0.001720,-0.036698
Fighting,-0.051171,0.051130,-0.073778,-0.048645,-0.071687,-0.039613,-0.068775,-0.080531,-0.061108,1.000000,...,-0.059483,-0.055090,-0.007791,-0.073778,-0.068775,0.051130,-0.065792,-0.048645,-0.071687,0.077786
Psychic,-0.094009,-0.061243,-0.099639,-0.111968,-0.112381,-0.103195,-0.091928,-0.079079,0.027227,0.000596,...,-0.042311,-0.069031,-0.044327,-0.099639,-0.091928,-0.061243,-0.070947,-0.111968,-0.112381,0.124688
Rock,-0.072829,-0.064677,0.011447,-0.003706,-0.106877,-0.081036,-0.072188,0.072085,0.002212,-0.055090,...,-0.017110,1.000000,-0.033493,0.011447,-0.072188,-0.064677,-0.069057,-0.003706,-0.106877,0.032731
Ghost,0.075316,-0.013459,-0.077314,-0.058915,-0.094420,0.008736,-0.041592,-0.035908,-0.056665,-0.065792,...,-0.029914,-0.069057,0.001484,-0.077314,-0.041592,-0.013459,1.000000,-0.058915,-0.094420,0.003641
Ice,-0.027476,-0.065851,0.000242,-0.070229,-0.085366,-0.064726,-0.033382,-0.003872,-0.051232,-0.059483,...,1.000000,-0.017110,-0.010163,0.000242,-0.033382,-0.065851,-0.029914,-0.070229,-0.085366,0.060248
Dragon,-0.078818,-0.038069,-0.083285,-0.081200,-0.098702,-0.055525,-0.024000,0.052430,-0.035541,-0.068775,...,0.015173,-0.032360,-0.003963,-0.083285,-0.024000,-0.038069,-0.019410,-0.081200,-0.098702,0.229705
Dark,-0.048339,-0.020368,-0.028548,-0.082062,-0.099751,-0.018227,-0.067375,-0.023480,-0.059864,-0.007791,...,-0.010163,-0.033493,1.000000,-0.028548,-0.067375,-0.020368,0.001484,-0.082062,-0.099751,0.056154
Steel,-0.061537,-0.056108,-0.096131,0.047178,-0.097645,-0.074036,-0.001346,-0.020771,0.013155,-0.005161,...,-0.057042,0.049202,-0.023978,-0.096131,-0.001346,-0.056108,0.026479,0.047178,-0.097645,0.109703
Flying,-0.081366,-0.028855,-0.092030,0.064571,0.125506,-0.067950,-0.020407,-0.060578,-0.052669,-0.086119,...,-0.049498,-0.048221,-0.022164,-0.092030,-0.020407,-0.028855,-0.061555,0.064571,0.125506,0.059383
Poison,0.110372,-0.085471,-0.073986,0.121210,-0.110800,1.000000,-0.074838,-0.053878,-0.066495,-0.039613,...,-0.064726,-0.081036,-0.018227,-0.073986,-0.074838,-0.085471,0.008736,0.121210,-0.110800,-0.090441
Flying,-0.081366,-0.028855,-0.092030,0.064571,0.125506,-0.067950,-0.020407,-0.060578,-0.052669,-0.086119,...,-0.049498,-0.048221,-0.022164,-0.092030,-0.020407,-0.028855,-0.061555,0.064571,0.125506,0.059383
Dragon,-0.078818,-0.038069,-0.083285,-0.081200,-0.098702,-0.055525,-0.024000,0.052430,-0.035541,-0.068775,...,0.015173,-0.032360,-0.003963,-0.083285,-0.024000,-0.038069,-0.019410,-0.081200,-0.098702,0.229705
Ground,-0.097033,-0.022621,-0.006844,-0.063544,-0.102044,-0.053878,-0.059420,1.000000,-0.069360,-0.080531,...,-0.003872,0.072085,-0.023480,-0.006844,-0.059420,-0.022621,-0.035908,-0.063544,-0.102044,0.015060
Fairy,-0.048756,-0.067651,-0.067703,-0.072148,-0.001720,-0.066495,-0.035541,-0.069360,1.000000,-0.061108,...,-0.051232,0.002212,-0.059864,-0.067703,-0.035541,-0.067651,-0.056665,-0.072148,-0.001720,-0.036698
Grass,1.000000,-0.108248,-0.126894,-0.034430,-0.117156,0.110372,-0.078818,-0.097033,-0.048756,-0.051171,...,-0.027476,-0.072829,-0.048339,-0.126894,-0.078818,-0.108248,0.075316,-0.034430,-0.117156,-0.052592
Fighting,-0.051171,0.051130,-0.073778,-0.048645,-0.071687,-0.039613,-0.068775,-0.080531,-0.061108,1.000000,...,-0.059483,-0.055090,-0.007791,-0.073778,-0.068775,0.051130,-0.065792,-0.048645,-0.071687,0.077786
Psychic,-0.094009,-0.061243,-0.099639,-0.111968,-0.112381,-0.103195,-0.091928,-0.079079,0.027227,0.000596,...,-0.042311,-0.069031,-0.044327,-0.099639,-0.091928,-0.061243,-0.070947,-0.111968,-0.112381,0.124688
Steel,-0.061537,-0.056108,-0.096131,0.047178,-0.097645,-0.074036,-0.001346,-0.020771,0.013155,-0.005161,...,-0.057042,0.049202,-0.023978,-0.096131,-0.001346,-0.056108,0.026479,0.047178,-0.097645,0.109703
Ice,-0.027476,-0.065851,0.000242,-0.070229,-0.085366,-0.064726,-0.033382,-0.003872,-0.051232,-0.059483,...,1.000000,-0.017110,-0.010163,0.000242,-0.033382,-0.065851,-0.029914,-0.070229,-0.085366,0.060248
Rock,-0.072829,-0.064677,0.011447,-0.003706,-0.106877,-0.081036,-0.072188,0.072085,0.002212,-0.055090,...,-0.017110,1.000000,-0.033493,0.011447,-0.072188,-0.064677,-0.069057,-0.003706,-0.106877,0.032731
Dark,-0.048339,-0.020368,-0.028548,-0.082062,-0.099751,-0.018227,-0.067375,-0.023480,-0.059864,-0.007791,...,-0.010163,-0.033493,1.000000,-0.028548,-0.067375,-0.020368,0.001484,-0.082062,-0.099751,0.056154
Water,-0.126894,-0.114850,1.000000,-0.123983,-0.154994,-0.073986,-0.069109,-0.006844,-0.067703,-0.073778,...,0.000242,0.011447,-0.028548,1.000000,-0.069109,-0.114850,-0.077314,-0.123983,-0.154994,-0.021665
Electric,-0.078818,-0.057104,-0.069109,-0.045111,-0.067737,-0.074838,1.000000,-0.059420,-0.035541,-0.068775,...,-0.033382,-0.072188,-0.067375,-0.069109,1.000000,-0.057104,-0.041592,-0.045111,-0.067737,0.020971
Fire,-0.108248,1.000000,-0.114850,-0.060536,-0.085097,-0.085471,-0.057104,-0.022621,-0.067651,0.051130,...,-0.065851,-0.064677,-0.020368,-0.114850,-0.057104,1.000000,-0.013459,-0.060536,-0.085097,0.078726
Ghost,0.075316,-0.013459,-0.077314,-0.058915,-0.094420,0.008736,-0.041592,-0.035908,-0.056665,-0.065792,...,-0.029914,-0.069057,0.001484,-0.077314,-0.041592,-0.013459,1.000000,-0.058915,-0.094420,0.003641
Bug,-0.034430,-0.060536,-0.123983,1.000000,-0.120219,0.121210,-0.045111,-0.063544,-0.072148,-0.048645,...,-0.070229,-0.003706,-0.082062,-0.123983,-0.045111,-0.060536,-0.058915,1.000000,-0.120219,-0.145781
Normal,-0.117156,-0.085097,-0.154994,-0.120219,1.000000,-0.110800,-0.067737,-0.102044,-0.001720,-0.071687,...,-0.085366,-0.106877,-0.099751,-0.154994,-0.067737,-0.085097,-0.094420,-0.120219,1.000000,-0.105331
Total,-0.052592,0.078726,-0.021665,-0.145781,-0.105331,-0.090441,0.020971,0.015060,-0.036698,0.077786,...,0.060248,0.032731,0.056154,-0.021665,0.020971,0.078726,0.003641,-0.145781,-0.105331,1.000000

In [65]:
result = cor_df.sort_values(by=['Total'], ascending=False)['Total'].index[1]
print("The #1 pokemon type that is most likely to have the highest Total is: ", result)

The #1 pokemon type that is most likely to have the highest Total is:  Dragon

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

Answer: If for a particular row the Type-1 value is more correlated to total then for that Type-1 will be chosen and vice-versa